
import React, { FC } from 'react'
import styles from './MainLoyout.module.css'
import Head from 'next/head';
import { Inter } from "next/font/google";
import Navbar from '../Navbar';

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children: React.ReactNode;
};

const MainLoyout: React.FC<Props> = ({children}: any) => {
  return (
    <>
      <Head>
        <title>Home - Mizael Soler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${inter.className}`}>
        {children}
      </main>
    </>
  );
}

export default MainLoyout
